EVTYPE <- data.frame(
    from = c(
        '?',
        'ABNORMALLY DRY',
        'ABNORMALLY WET',
        'ABNORMAL WARMTH',
        'ACCUMULATED SNOWFALL',
        'AGRICULTURAL FREEZE',
        'APACHE COUNTY',
        'ASTRONOMICAL HIGH TIDE',
        'ASTRONOMICAL LOW TIDE',
        'AVALANCE',
        'AVALANCHE',
        'BEACH EROSIN',
        'Beach Erosion',
        'BEACH EROSION',
        'BEACH EROSION/COASTAL FLOOD',
        'BEACH FLOOD',
        'BELOW NORMAL PRECIPITATION',
        'BITTER WIND CHILL',
        'BITTER WIND CHILL TEMPERATURES',
        'Black Ice',
        'BLACK ICE',
        'BLIZZARD',
        'BLIZZARD AND EXTREME WIND CHIL',
        'BLIZZARD AND HEAVY SNOW',
        'BLIZZARD/FREEZING RAIN',
        'BLIZZARD/HEAVY SNOW',
        'BLIZZARD/HIGH WIND',
        'Blizzard Summary',
        'BLIZZARD WEATHER',
        'BLIZZARD/WINTER STORM',
        'BLOWING DUST',
        'blowing snow',
        'Blowing Snow',
        'BLOWING SNOW',
        'BLOWING SNOW & EXTREME WIND CH',
        'BLOWING SNOW- EXTREME WIND CHI',
        'BLOWING SNOW/EXTREME WIND CHIL',
        'BLOW-OUT TIDE',
        'BLOW-OUT TIDES',
        'BREAKUP FLOODING',
        'BRUSH FIRE',
        'BRUSH FIRES',
        'COASTAL EROSION',
        'Coastal Flood',
        'COASTALFLOOD',
        'COASTAL FLOOD',
        'coastal flooding',
        'Coastal Flooding',
        'COASTAL FLOODING',
        'COASTAL  FLOODING/EROSION',
        'COASTAL FLOODING/EROSION',
        'Coastal Storm',
        'COASTALSTORM',
        'COASTAL STORM',
        'COASTAL SURGE',
        'COASTAL/TIDAL FLOOD',
        'Cold',
        'COLD',
        'COLD AIR FUNNEL',
        'COLD AIR FUNNELS',
        'COLD AIR TORNADO',
        'Cold and Frost',
        'COLD AND FROST',
        'COLD AND SNOW',
        'COLD AND WET CONDITIONS',
        'Cold Temperature',
        'COLD TEMPERATURES',
        'COLD WAVE',
        'COLD WEATHER',
        'COLD/WIND CHILL',
        'COLD WIND CHILL TEMPERATURES',
        'COLD/WINDS',
        'COOL AND WET',
        'COOL SPELL',
        'CSTL FLOODING/EROSION',
        'Damaging Freeze',
        'DAMAGING FREEZE',
        'DAM BREAK',
        'DAM FAILURE',
        'DEEP HAIL',
        'DENSE FOG',
        'DENSE SMOKE',
        'DOWNBURST',
        'DOWNBURST WINDS',
        'DRIEST MONTH',
        'Drifting Snow',
        'DROUGHT',
        'DROUGHT/EXCESSIVE HEAT',
        'DROWNING',
        'DRY',
        'DRY CONDITIONS',
        'DRY HOT WEATHER',
        'DRY MICROBURST',
        'DRY MICROBURST 50',
        'DRY MICROBURST 53',
        'DRY MICROBURST 58',
        'DRY MICROBURST 61',
        'DRY MICROBURST 84',
        'DRY MICROBURST WINDS',
        'DRY MIRCOBURST WINDS',
        'DRYNESS',
        'DRY PATTERN',
        'DRY SPELL',
        'DRY WEATHER',
        'DUST DEVEL',
        'Dust Devil',
        'DUST DEVIL',
        'DUST DEVIL WATERSPOUT',
        'DUSTSTORM',
        'DUST STORM',
        'DUST STORM/HIGH WINDS',
        'EARLY FREEZE',
        'Early Frost',
        'EARLY FROST',
        'EARLY RAIN',
        'EARLY SNOW',
        'Early snowfall',
        'EARLY SNOWFALL',
        'Erosion/Cstl Flood',
        'EXCESSIVE',
        'Excessive Cold',
        'EXCESSIVE HEAT',
        'EXCESSIVE HEAT/DROUGHT',
        'EXCESSIVELY DRY',
        'EXCESSIVE PRECIPITATION',
        'EXCESSIVE RAIN',
        'EXCESSIVE RAINFALL',
        'EXCESSIVE SNOW',
        'EXCESSIVE WETNESS',
        'Extended Cold',
        'Extreme Cold',
        'EXTREME COLD',
        'EXTREME COLD/WIND CHILL',
        'EXTREME HEAT',
        'EXTREMELY WET',
        'EXTREME/RECORD COLD',
        'EXTREME WINDCHILL',
        'EXTREME WIND CHILL',
        'EXTREME WIND CHILL/BLOWING SNO',
        'EXTREME WIND CHILLS',
        'EXTREME WINDCHILL TEMPERATURES',
        'FALLING SNOW/ICE',
        'FIRST FROST',
        'FIRST SNOW',
        'FLASH FLOOD',
        'FLASH FLOOD/',
        'FLASH FLOOD/FLOOD',
        'FLASH FLOOD/ FLOOD',
        'FLASH FLOOD FROM ICE JAMS',
        'FLASH FLOOD - HEAVY RAIN',
        'FLASH FLOOD/HEAVY RAIN',
        'FLASH FLOODING',
        'FLASH FLOODING/FLOOD',
        'FLASH FLOODING/THUNDERSTORM WI',
        'FLASH FLOOD/LANDSLIDE',
        'FLASH FLOOD LANDSLIDES',
        'FLASH FLOODS',
        'FLASH FLOOD/ STREET',
        'FLASH FLOOD WINDS',
        'FLASH FLOOODING',
        'Flood',
        'FLOOD',
        'FLOOD FLASH',
        'FLOOD/FLASH',
        'Flood/Flash Flood',
        'FLOOD/FLASHFLOOD',
        'FLOOD/FLASH FLOOD',
        'FLOOD/FLASH/FLOOD',
        'FLOOD/FLASH FLOODING',
        'FLOOD FLOOD/FLASH',
        'FLOOD & HEAVY RAIN',
        'FLOODING',
        'FLOODING/HEAVY RAIN',
        'FLOOD/RAIN/WIND',
        'FLOOD/RAIN/WINDS',
        'FLOOD/RIVER FLOOD',
        'FLOODS',
        'Flood/Strong Wind',
        'FLOOD WATCH/',
        'FOG',
        'FOG AND COLD TEMPERATURES',
        'FOREST FIRES',
        'Freeze',
        'FREEZE',
        'Freezing drizzle',
        'Freezing Drizzle',
        'FREEZING DRIZZLE',
        'FREEZING DRIZZLE AND FREEZING',
        'Freezing Fog',
        'FREEZING FOG',
        'Freezing rain',
        'Freezing Rain',
        'FREEZING RAIN',
        'FREEZING RAIN AND SLEET',
        'FREEZING RAIN AND SNOW',
        'FREEZING RAIN/SLEET',
        'FREEZING RAIN SLEET AND',
        'FREEZING RAIN SLEET AND LIGHT',
        'FREEZING RAIN/SNOW',
        'Freezing Spray',
        'Frost',
        'FROST',
        'Frost/Freeze',
        'FROST/FREEZE',
        'FROST\\FREEZE',
        'FUNNEL',
        'Funnel Cloud',
        'FUNNEL CLOUD',
        'FUNNEL CLOUD.',
        'FUNNEL CLOUD/HAIL',
        'FUNNEL CLOUDS',
        'FUNNELS',
        'Glaze',
        'GLAZE',
        'GLAZE ICE',
        'GLAZE/ICE STORM',
        'gradient wind',
        'Gradient wind',
        'GRADIENT WIND',
        'GRADIENT WINDS',
        'GRASS FIRES',
        'GROUND BLIZZARD',
        'GUSTNADO',
        'GUSTNADO AND',
        'GUSTY LAKE WIND',
        'GUSTY THUNDERSTORM WIND',
        'GUSTY THUNDERSTORM WINDS',
        'Gusty Wind',
        'GUSTY WIND',
        'GUSTY WIND/HAIL',
        'GUSTY WIND/HVY RAIN',
        'Gusty wind/rain',
        'Gusty winds',
        'Gusty Winds',
        'GUSTY WINDS',
        'HAIL',
        'Hail(0.75)',
        'HAIL 075',
        'HAIL 0.75',
        'HAIL 088',
        'HAIL 0.88',
        'HAIL 100',
        'HAIL 1.00',
        'HAIL 125',
        'HAIL 150',
        'HAIL 175',
        'HAIL 1.75',
        'HAIL 1.75)',
        'HAIL 200',
        'HAIL 225',
        'HAIL 275',
        'HAIL 450',
        'HAIL 75',
        'HAIL 80',
        'HAIL 88',
        'HAIL ALOFT',
        'HAIL DAMAGE',
        'HAIL FLOODING',
        'HAIL/ICY ROADS',
        'HAILSTORM',
        'HAIL STORM',
        'HAILSTORMS',
        'HAIL/WIND',
        'HAIL/WINDS',
        'HARD FREEZE',
        'HAZARDOUS SURF',
        'HEAT',
        'Heatburst',
        'HEAT DROUGHT',
        'HEAT/DROUGHT',
        'Heat Wave',
        'HEAT WAVE',
        'HEAT WAVE DROUGHT',
        'HEAT WAVES',
        'HEAVY LAKE SNOW',
        'HEAVY MIX',
        'HEAVY PRECIPATATION',
        'Heavy Precipitation',
        'HEAVY PRECIPITATION',
        'Heavy rain',
        'Heavy Rain',
        'HEAVY RAIN',
        'HEAVY RAIN AND FLOOD',
        'Heavy Rain and Wind',
        'HEAVY RAIN EFFECTS',
        'HEAVY RAINFALL',
        'HEAVY RAIN/FLOODING',
        'Heavy Rain/High Surf',
        'HEAVY RAIN/LIGHTNING',
        'HEAVY RAIN/MUDSLIDES/FLOOD',
        'HEAVY RAINS',
        'HEAVY RAIN/SEVERE WEATHER',
        'HEAVY RAINS/FLOODING',
        'HEAVY RAIN/SMALL STREAM URBAN',
        'HEAVY RAIN/SNOW',
        'HEAVY RAIN/URBAN FLOOD',
        'HEAVY RAIN; URBAN FLOOD WINDS;',
        'HEAVY RAIN/WIND',
        'HEAVY SEAS',
        'HEAVY SHOWER',
        'HEAVY SHOWERS',
        'HEAVY SNOW',
        'HEAVY SNOW AND',
        'HEAVY SNOW ANDBLOWING SNOW',
        'HEAVY SNOW AND HIGH WINDS',
        'HEAVY SNOW AND ICE',
        'HEAVY SNOW AND ICE STORM',
        'HEAVY SNOW AND STRONG WINDS',
        'HEAVY SNOW/BLIZZARD',
        'HEAVY SNOW/BLIZZARD/AVALANCHE',
        'HEAVY SNOW/BLOWING SNOW',
        'HEAVY SNOW   FREEZING RAIN',
        'HEAVY SNOW/FREEZING RAIN',
        'HEAVY SNOW/HIGH',
        'HEAVY SNOW/HIGH WIND',
        'HEAVY SNOW/HIGH WINDS',
        'HEAVY SNOW/HIGH WINDS & FLOOD',
        'HEAVY SNOW/HIGH WINDS/FREEZING',
        'HEAVY SNOW & ICE',
        'HEAVY SNOW/ICE',
        'HEAVY SNOW/ICE STORM',
        'HEAVY SNOWPACK',
        'Heavy snow shower',
        'HEAVY SNOW/SLEET',
        'HEAVY SNOW SQUALLS',
        'HEAVY SNOW-SQUALLS',
        'HEAVY SNOW/SQUALLS',
        'HEAVY SNOW/WIND',
        'HEAVY SNOW/WINTER STORM',
        'Heavy Surf',
        'HEAVY SURF',
        'Heavy surf and wind',
        'HEAVY SURF COASTAL FLOODING',
        'HEAVY SURF/HIGH SURF',
        'HEAVY SWELLS',
        'HEAVY WET SNOW',
        'HIGH',
        'HIGH SEAS',
        'High Surf',
        'HIGH SURF',
        'HIGH SURF ADVISORIES',
        'HIGH SURF ADVISORY',
        'HIGH SWELLS',
        'HIGH  SWELLS',
        'HIGH TEMPERATURE RECORD',
        'HIGH TIDES',
        'HIGH WATER',
        'HIGH WAVES',
        'HIGHWAY FLOODING',
        'High Wind',
        'HIGH WIND',
        'HIGH WIND 48',
        'HIGH WIND 63',
        'HIGH WIND 70',
        'HIGH WIND AND HEAVY SNOW',
        'HIGH WIND AND HIGH TIDES',
        'HIGH WIND AND SEAS',
        'HIGH WIND/BLIZZARD',
        'HIGH WIND/ BLIZZARD',
        'HIGH WIND/BLIZZARD/FREEZING RA',
        'HIGH WIND DAMAGE',
        'HIGH WIND (G40)',
        'HIGH WIND/HEAVY SNOW',
        'HIGH WIND/LOW WIND CHILL',
        'HIGH WINDS',
        'HIGH  WINDS',
        'HIGH WINDS/',
        'HIGH WINDS 55',
        'HIGH WINDS 57',
        'HIGH WINDS 58',
        'HIGH WINDS 63',
        'HIGH WINDS 66',
        'HIGH WINDS 67',
        'HIGH WINDS 73',
        'HIGH WINDS 76',
        'HIGH WINDS 80',
        'HIGH WINDS 82',
        'HIGH WINDS AND WIND CHILL',
        'HIGH WINDS/COASTAL FLOOD',
        'HIGH WINDS/COLD',
        'HIGH WINDS DUST STORM',
        'HIGH WIND/SEAS',
        'HIGH WINDS/FLOODING',
        'HIGH WINDS/HEAVY RAIN',
        'HIGH WINDS HEAVY RAINS',
        'HIGH WINDS/SNOW',
        'HIGH WIND/WIND CHILL',
        'HIGH WIND/WIND CHILL/BLIZZARD',
        'Hot and Dry',
        'HOT/DRY PATTERN',
        'HOT PATTERN',
        'HOT SPELL',
        'HOT WEATHER',
        'HURRICANE',
        'Hurricane Edouard',
        'HURRICANE EMILY',
        'HURRICANE ERIN',
        'HURRICANE FELIX',
        'HURRICANE-GENERATED SWELLS',
        'HURRICANE GORDON',
        'HURRICANE OPAL',
        'HURRICANE OPAL/HIGH WINDS',
        'HURRICANE/TYPHOON',
        'HVY RAIN',
        'HYPERTHERMIA/EXPOSURE',
        'HYPOTHERMIA',
        'Hypothermia/Exposure',
        'HYPOTHERMIA/EXPOSURE',
        'ICE',
        'ICE AND SNOW',
        'ICE FLOES',
        'Ice Fog',
        'ICE JAM',
        'ICE JAM FLOODING',
        'Ice jam flood (minor',
        'ICE ON ROAD',
        'ICE PELLETS',
        'ICE ROADS',
        'Ice/Snow',
        'ICE/SNOW',
        'ICE STORM',
        'ICE STORM AND SNOW',
        'Icestorm/Blizzard',
        'ICE STORM/FLASH FLOOD',
        'ICE/STRONG WINDS',
        'Icy Roads',
        'ICY ROADS',
        'LACK OF SNOW',
        'Lake Effect Snow',
        'LAKE EFFECT SNOW',
        'LAKE-EFFECT SNOW',
        'LAKE FLOOD',
        'LAKESHORE FLOOD',
        'LANDSLIDE',
        'LANDSLIDES',
        'LANDSLIDE/URBAN FLOOD',
        'Landslump',
        'LANDSLUMP',
        'LANDSPOUT',
        'LARGE WALL CLOUD',
        'LATE FREEZE',
        'LATE SEASON HAIL',
        'LATE SEASON SNOW',
        'Late-season Snowfall',
        'Late Season Snowfall',
        'LATE SNOW',
        'LIGHT FREEZING RAIN',
        'LIGHTING',
        'LIGHTNING',
        'LIGHTNING.',
        'LIGHTNING AND HEAVY RAIN',
        'LIGHTNING AND THUNDERSTORM WIN',
        'LIGHTNING AND WINDS',
        'LIGHTNING DAMAGE',
        'LIGHTNING FIRE',
        'LIGHTNING/HEAVY RAIN',
        'LIGHTNING INJURY',
        'LIGHTNING THUNDERSTORM WINDS',
        'LIGHTNING THUNDERSTORM WINDSS',
        'LIGHTNING  WAUSEON',
        'Light snow',
        'Light Snow',
        'LIGHT SNOW',
        'LIGHT SNOW AND SLEET',
        'Light Snowfall',
        'Light Snow/Flurries',
        'LIGHT SNOW/FREEZING PRECIP',
        'LIGNTNING',
        'LOCAL FLASH FLOOD',
        'LOCAL FLOOD',
        'LOCALLY HEAVY RAIN',
        'LOW TEMPERATURE',
        'LOW TEMPERATURE RECORD',
        'LOW WIND CHILL',
        'MAJOR FLOOD',
        'Marine Accident',
        'MARINE HAIL',
        'MARINE HIGH WIND',
        'MARINE MISHAP',
        'MARINE STRONG WIND',
        'MARINE THUNDERSTORM WIND',
        'MARINE TSTM WIND',
        'Metro Storm, May 26',
        'Microburst',
        'MICROBURST',
        'MICROBURST WINDS',
        'Mild and Dry Pattern',
        'MILD/DRY PATTERN',
        'MILD PATTERN',
        'MINOR FLOOD',
        'Minor Flooding',
        'MINOR FLOODING',
        'MIXED PRECIP',
        'Mixed Precipitation',
        'MIXED PRECIPITATION',
        'MODERATE SNOW',
        'MODERATE SNOWFALL',
        'MONTHLY PRECIPITATION',
        'Monthly Rainfall',
        'MONTHLY RAINFALL',
        'Monthly Snowfall',
        'MONTHLY SNOWFALL',
        'MONTHLY TEMPERATURE',
        'Mountain Snows',
        'MUD/ROCK SLIDE',
        'Mudslide',
        'MUDSLIDE',
        'MUD SLIDE',
        'MUDSLIDE/LANDSLIDE',
        'Mudslides',
        'MUDSLIDES',
        'MUD SLIDES',
        'MUD SLIDES URBAN FLOODING',
        'NEAR RECORD SNOW',
        'NONE',
        'NON SEVERE HAIL',
        'NON-SEVERE WIND DAMAGE',
        'NON TSTM WIND',
        'NON-TSTM WIND',
        'NORMAL PRECIPITATION',
        'NORTHERN LIGHTS',
        'No Severe Weather',
        'Other',
        'OTHER',
        'PATCHY DENSE FOG',
        'PATCHY ICE',
        'Prolong Cold',
        'PROLONG COLD',
        'PROLONG COLD/SNOW',
        'PROLONGED RAIN',
        'PROLONG WARMTH',
        'RAIN',
        'RAIN AND WIND',
        'Rain Damage',
        'RAIN (HEAVY)',
        'RAIN/SNOW',
        'RAINSTORM',
        'RAIN/WIND',
        'RAPIDLY RISING WATER',
        'Record Cold',
        'RECORD COLD',
        'RECORD  COLD',
        'RECORD COLD AND HIGH WIND',
        'RECORD COLD/FROST',
        'RECORD COOL',
        'Record dry month',
        'RECORD DRYNESS',
        'RECORD/EXCESSIVE HEAT',
        'RECORD/EXCESSIVE RAINFALL',
        'Record Heat',
        'RECORD HEAT',
        'RECORD HEAT WAVE',
        'Record High',
        'RECORD HIGH',
        'RECORD HIGH TEMPERATURE',
        'RECORD HIGH TEMPERATURES',
        'RECORD LOW',
        'RECORD LOW RAINFALL',
        'Record May Snow',
        'RECORD PRECIPITATION',
        'RECORD RAINFALL',
        'RECORD SNOW',
        'RECORD SNOW/COLD',
        'RECORD SNOWFALL',
        'Record temperature',
        'RECORD TEMPERATURE',
        'Record Temperatures',
        'RECORD TEMPERATURES',
        'RECORD WARM',
        'RECORD WARM TEMPS.',
        'Record Warmth',
        'RECORD WARMTH',
        'Record Winter Snow',
        'RED FLAG CRITERIA',
        'RED FLAG FIRE WX',
        'REMNANTS OF FLOYD',
        'RIP CURRENT',
        'RIP CURRENTS',
        'RIP CURRENTS HEAVY SURF',
        'RIP CURRENTS/HEAVY SURF',
        'RIVER AND STREAM FLOOD',
        'RIVER FLOOD',
        'River Flooding',
        'RIVER FLOODING',
        'ROCK SLIDE',
        'ROGUE WAVE',
        'ROTATING WALL CLOUD',
        'ROUGH SEAS',
        'ROUGH SURF',
        'RURAL FLOOD',
        'Saharan Dust',
        'SAHARAN DUST',
        'Seasonal Snowfall',
        'SEICHE',
        'SEVERE COLD',
        'SEVERE THUNDERSTORM',
        'SEVERE THUNDERSTORMS',
        'SEVERE THUNDERSTORM WINDS',
        'SEVERE TURBULENCE',
        'SLEET',
        'SLEET & FREEZING RAIN',
        'SLEET/FREEZING RAIN',
        'SLEET/ICE STORM',
        'SLEET/RAIN/SNOW',
        'SLEET/SNOW',
        'SLEET STORM',
        'small hail',
        'Small Hail',
        'SMALL HAIL',
        'SMALL STREAM',
        'SMALL STREAM AND',
        'SMALL STREAM AND URBAN FLOOD',
        'SMALL STREAM AND URBAN FLOODIN',
        'SMALL STREAM FLOOD',
        'SMALL STREAM FLOODING',
        'SMALL STREAM URBAN FLOOD',
        'SMALL STREAM/URBAN FLOOD',
        'Sml Stream Fld',
        'SMOKE',
        'Snow',
        'SNOW',
        'Snow Accumulation',
        'SNOW ACCUMULATION',
        'SNOW ADVISORY',
        'SNOW AND COLD',
        'SNOW AND HEAVY SNOW',
        'Snow and Ice',
        'SNOW AND ICE',
        'SNOW AND ICE STORM',
        'Snow and sleet',
        'SNOW AND SLEET',
        'SNOW AND WIND',
        'SNOW/ BITTER COLD',
        'SNOW/BLOWING SNOW',
        'SNOW/COLD',
        'SNOW\\COLD',
        'SNOW DROUGHT',
        'SNOWFALL RECORD',
        'SNOW FREEZING RAIN',
        'SNOW/FREEZING RAIN',
        'SNOW/HEAVY SNOW',
        'SNOW/HIGH WINDS',
        'SNOW- HIGH WIND- WIND CHILL',
        'SNOW/ICE',
        'SNOW/ ICE',
        'SNOW/ICE STORM',
        'SNOWMELT FLOODING',
        'SNOW/RAIN',
        'SNOW/RAIN/SLEET',
        'SNOW SHOWERS',
        'SNOW SLEET',
        'SNOW/SLEET',
        'SNOW/SLEET/FREEZING RAIN',
        'SNOW/SLEET/RAIN',
        'SNOW SQUALL',
        'Snow squalls',
        'Snow Squalls',
        'SNOW SQUALLS',
        'SNOWSTORM',
        'SOUTHEAST',
        'STORM FORCE WINDS',
        'STORM SURGE',
        'STORM SURGE/TIDE',
        'STREAM FLOODING',
        'STREET FLOOD',
        'STREET FLOODING',
        'Strong Wind',
        'STRONG WIND',
        'STRONG WIND GUST',
        'Strong winds',
        'Strong Winds',
        'STRONG WINDS',
        'Summary August 10',
        'Summary August 11',
        'Summary August 17',
        'Summary August 21',
        'Summary August 2-3',
        'Summary August 28',
        'Summary August 4',
        'Summary August 7',
        'Summary August 9',
        'Summary Jan 17',
        'Summary July 23-24',
        'Summary June 18-19',
        'Summary June 5-6',
        'Summary June 6',
        'Summary: Nov. 16',
        'Summary: Nov. 6-7',
        'Summary: Oct. 20-21',
        'Summary: October 31',
        'Summary of April 12',
        'Summary of April 13',
        'Summary of April 21',
        'Summary of April 27',
        'Summary of April 3rd',
        'Summary of August 1',
        'Summary of July 11',
        'Summary of July 2',
        'Summary of July 22',
        'Summary of July 26',
        'Summary of July 29',
        'Summary of July 3',
        'Summary of June 10',
        'Summary of June 11',
        'Summary of June 12',
        'Summary of June 13',
        'Summary of June 15',
        'Summary of June 16',
        'Summary of June 18',
        'Summary of June 23',
        'Summary of June 24',
        'Summary of June 3',
        'Summary of June 30',
        'Summary of June 4',
        'Summary of June 6',
        'Summary of March 14',
        'Summary of March 23',
        'Summary of March 24',
        'SUMMARY OF MARCH 24-25',
        'SUMMARY OF MARCH 27',
        'SUMMARY OF MARCH 29',
        'Summary of May 10',
        'Summary of May 13',
        'Summary of May 14',
        'Summary of May 22',
        'Summary of May 22 am',
        'Summary of May 22 pm',
        'Summary of May 26 am',
        'Summary of May 26 pm',
        'Summary of May 31 am',
        'Summary of May 31 pm',
        'Summary of May 9-10',
        'Summary: Sept. 18',
        'Summary Sept. 25-26',
        'Summary September 20',
        'Summary September 23',
        'Summary September 3',
        'Summary September 4',
        'Temperature record',
        'THUDERSTORM WINDS',
        'THUNDEERSTORM WINDS',
        'THUNDERESTORM WINDS',
        'THUNDERSNOW',
        'Thundersnow shower',
        'THUNDERSTORM',
        'THUNDERSTORM DAMAGE',
        'THUNDERSTORM DAMAGE TO',
        'THUNDERSTORM HAIL',
        'THUNDERSTORMS',
        'THUNDERSTORMS WIND',
        'THUNDERSTORMS WINDS',
        'THUNDERSTORMW',
        'THUNDERSTORMW 50',
        'Thunderstorm Wind',
        'THUNDERSTORM WIND',
        'THUNDERSTORM WIND.',
        'THUNDERSTORM WIND 50',
        'THUNDERSTORM WIND 52',
        'THUNDERSTORM WIND 56',
        'THUNDERSTORM WIND 59',
        'THUNDERSTORM WIND 59 MPH',
        'THUNDERSTORM WIND 59 MPH.',
        'THUNDERSTORM WIND 60 MPH',
        'THUNDERSTORM WIND 65MPH',
        'THUNDERSTORM WIND 65 MPH',
        'THUNDERSTORM WIND 69',
        'THUNDERSTORM WIND 98 MPH',
        'THUNDERSTORM WIND/AWNING',
        'THUNDERSTORM WIND (G40)',
        'THUNDERSTORM WIND G50',
        'THUNDERSTORM WIND G51',
        'THUNDERSTORM WIND G52',
        'THUNDERSTORM WIND G55',
        'THUNDERSTORM WIND G60',
        'THUNDERSTORM WIND G61',
        'THUNDERSTORM WIND/HAIL',
        'THUNDERSTORM WIND/LIGHTNING',
        'THUNDERSTORMWINDS',
        'THUNDERSTORM WINDS',
        'THUNDERSTORM  WINDS',
        'THUNDERSTORM W INDS',
        'THUNDERSTORM WINDS.',
        'THUNDERSTORM WINDS 13',
        'THUNDERSTORM WINDS 2',
        'THUNDERSTORM WINDS 50',
        'THUNDERSTORM WINDS 52',
        'THUNDERSTORM WINDS53',
        'THUNDERSTORM WINDS 53',
        'THUNDERSTORM WINDS 60',
        'THUNDERSTORM WINDS 61',
        'THUNDERSTORM WINDS 62',
        'THUNDERSTORM WINDS 63 MPH',
        'THUNDERSTORM WINDS AND',
        'THUNDERSTORM WINDS/FLASH FLOOD',
        'THUNDERSTORM WINDS/ FLOOD',
        'THUNDERSTORM WINDS/FLOODING',
        'THUNDERSTORM WINDS FUNNEL CLOU',
        'THUNDERSTORM WINDS/FUNNEL CLOU',
        'THUNDERSTORM WINDS G',
        'THUNDERSTORM WINDS G60',
        'THUNDERSTORM WINDSHAIL',
        'THUNDERSTORM WINDS HAIL',
        'THUNDERSTORM WINDS/HAIL',
        'THUNDERSTORM WINDS/ HAIL',
        'THUNDERSTORM WINDS HEAVY RAIN',
        'THUNDERSTORM WINDS/HEAVY RAIN',
        'THUNDERSTORM WINDS      LE CEN',
        'THUNDERSTORM WINDS LIGHTNING',
        'THUNDERSTORM WINDSS',
        'THUNDERSTORM WINDS SMALL STREA',
        'THUNDERSTORM WINDS URBAN FLOOD',
        'THUNDERSTORM WIND/ TREE',
        'THUNDERSTORM WIND TREES',
        'THUNDERSTORM WIND/ TREES',
        'THUNDERSTORM WINS',
        'THUNDERSTORMW WINDS',
        'THUNDERSTROM WIND',
        'THUNDERSTROM WINDS',
        'THUNDERTORM WINDS',
        'THUNDERTSORM WIND',
        'THUNDESTORM WINDS',
        'THUNERSTORM WINDS',
        'TIDAL FLOOD',
        'Tidal Flooding',
        'TIDAL FLOODING',
        'TORNADO',
        'TORNADO DEBRIS',
        'TORNADOES',
        'TORNADOES, TSTM WIND, HAIL',
        'TORNADO F0',
        'TORNADO F1',
        'TORNADO F2',
        'TORNADO F3',
        'TORNADOS',
        'TORNADO/WATERSPOUT',
        'TORNDAO',
        'TORRENTIAL RAIN',
        'Torrential Rainfall',
        'TROPICAL DEPRESSION',
        'TROPICAL STORM',
        'TROPICAL STORM ALBERTO',
        'TROPICAL STORM DEAN',
        'TROPICAL STORM GORDON',
        'TROPICAL STORM JERRY',
        'TSTM',
        'TSTM HEAVY RAIN',
        'TSTMW',
        'Tstm Wind',
        'TSTM WIND',
        'TSTM WIND 40',
        'TSTM WIND (41)',
        'TSTM WIND 45',
        'TSTM WIND 50',
        'TSTM WIND 51',
        'TSTM WIND 52',
        'TSTM WIND 55',
        'TSTM WIND 65)',
        'TSTM WIND AND LIGHTNING',
        'TSTM WIND DAMAGE',
        'TSTM WIND (G35)',
        'TSTM WIND (G40)',
        'TSTM WIND G45',
        'TSTM WIND  (G45)',
        'TSTM WIND (G45)',
        'TSTM WIND G58',
        'TSTM WIND/HAIL',
        'TSTM WINDS',
        'TSTM WND',
        'TSUNAMI',
        'TUNDERSTORM WIND',
        'TYPHOON',
        'Unseasonable Cold',
        'UNSEASONABLY COLD',
        'UNSEASONABLY COOL',
        'UNSEASONABLY COOL & WET',
        'UNSEASONABLY DRY',
        'UNSEASONABLY HOT',
        'UNSEASONABLY WARM',
        'UNSEASONABLY WARM AND DRY',
        'UNSEASONABLY WARM & WET',
        'UNSEASONABLY WARM/WET',
        'UNSEASONABLY WARM YEAR',
        'UNSEASONABLY WET',
        'UNSEASONAL LOW TEMP',
        'UNSEASONAL RAIN',
        'UNUSUALLY COLD',
        'UNUSUALLY LATE SNOW',
        'UNUSUALLY WARM',
        'UNUSUAL/RECORD WARMTH',
        'UNUSUAL WARMTH',
        'URBAN AND SMALL',
        'URBAN AND SMALL STREAM',
        'URBAN AND SMALL STREAM FLOOD',
        'URBAN AND SMALL STREAM FLOODIN',
        'Urban flood',
        'Urban Flood',
        'URBAN FLOOD',
        'Urban Flooding',
        'URBAN FLOODING',
        'URBAN FLOOD LANDSLIDE',
        'URBAN FLOODS',
        'URBAN SMALL',
        'URBAN/SMALL',
        'URBAN/SMALL FLOODING',
        'URBAN/SMALL STREAM',
        'URBAN SMALL STREAM FLOOD',
        'URBAN/SMALL STREAM FLOOD',
        'URBAN/SMALL STREAM  FLOOD',
        'URBAN/SMALL STREAM FLOODING',
        'URBAN/SMALL STRM FLDG',
        'URBAN/SML STREAM FLD',
        'URBAN/SML STREAM FLDG',
        'URBAN/STREET FLOODING',
        'VERY DRY',
        'VERY WARM',
        'VOG',
        'Volcanic Ash',
        'VOLCANIC ASH',
        'VOLCANIC ASHFALL',
        'Volcanic Ash Plume',
        'VOLCANIC ERUPTION',
        'WAKE LOW WIND',
        'WALL CLOUD',
        'WALL CLOUD/FUNNEL CLOUD',
        'WARM DRY CONDITIONS',
        'WARM WEATHER',
        'WATERSPOUT',
        'WATER SPOUT',
        'WATERSPOUT-',
        'WATERSPOUT/',
        'WATERSPOUT FUNNEL CLOUD',
        'WATERSPOUTS',
        'WATERSPOUT TORNADO',
        'WATERSPOUT-TORNADO',
        'WATERSPOUT/TORNADO',
        'WATERSPOUT/ TORNADO',
        'WAYTERSPOUT',
        'wet micoburst',
        'WET MICROBURST',
        'Wet Month',
        'WET SNOW',
        'WET WEATHER',
        'Wet Year',
        'Whirlwind',
        'WHIRLWIND',
        'WILDFIRE',
        'WILDFIRES',
        'WILD FIRES',
        'WILD/FOREST FIRE',
        'WILD/FOREST FIRES',
        'Wind',
        'WIND',
        'WIND ADVISORY',
        'WIND AND WAVE',
        'WIND CHILL',
        'WIND CHILL/HIGH WIND',
        'Wind Damage',
        'WIND DAMAGE',
        'WIND GUSTS',
        'WIND/HAIL',
        'WINDS',
        'WIND STORM',
        'WINTER MIX',
        'WINTER STORM',
        'WINTER STORM/HIGH WIND',
        'WINTER STORM HIGH WINDS',
        'WINTER STORM/HIGH WINDS',
        'WINTER STORMS',
        'Winter Weather',
        'WINTER WEATHER',
        'WINTER WEATHER MIX',
        'WINTER WEATHER/MIX',
        'WINTERY MIX',
        'Wintry mix',
        'Wintry Mix',
        'WINTRY MIX',
        'WND'
    ),
    to = c(
        'Unknown',
        'Abnormally dry',
        'Abnormally wet',
        'Abnormal warmth',
        'Accumulated snowfall',
        'Agricultural freeze',
        'apache county',
        'Astronomical high tide',
        'Astronomical low tide',
        'Avalanche',
        'Avalanche',
        'Beach erosion',
        'Beach erosion',
        'Beach erosion',
        'Beach erosion/Coastal flood',
        'Beach flood',
        'Below normal precipitation',
        'Bitter wind chill',
        'Bitter wind chill temperatures',
        'Black ice',
        'Black ice',
        'Blizzard',
        'Blizzard/Extreme wind chill',
        'Blizzard/Heavy snow',
        'Blizzard/Freezing rain',
        'Blizzard/Heavy snow',
        'Blizzard/High wind',
        'Blizzard summary',
        'Blizzard weather',
        'Blizzard/Winter storm',
        'Blowing dust',
        'Blowing snow',
        'Blowing snow',
        'Blowing snow',
        'Blowing snow/extreme wind chill',
        'Blowing snow/extreme wind chill',
        'Blowing snow/extreme wind chill',
        'Blow-out tide',
        'Blow-out tide',
        'Breakup flooding',
        'Brush fire',
        'Brush fire',
        'Coastal erosion',
        'Coastal flood',
        'Coastal flood',
        'Coastal flood',
        'Coastal flood',
        'Coastal flood',
        'Coastal flood',
        'Coastal flood/Erosion',
        'Coastal flood/Erosion',
        'Coastal storm',
        'Coastal storm',
        'Coastal storm',
        'Coastal surge',
        'Coastal/Tidal flood',
        'Cold',
        'Cold',
        'Cold air funnel',
        'Cold air funnel',
        'Cold air tornado',
        'Cold/Frost',
        'Cold/Frost',
        'Cold/Snow',
        'Cold/Wet conditions',
        'Cold temperature',
        'Cold temperature',
        'Cold wave',
        'Cold weather',
        'Cold/Wind chill',
        'Cold/Wind chill',
        'cold/winds',
        'Cool/Wet',
        'Cool spell',
        'Coastal flood/Erosion',
        'Damaging freeze',
        'Damaging freeze',
        'Dam failure',
        'Dam failure',
        'Deep hail',
        'Dense fog',
        'Dense smoke',
        'Downburst winds',
        'Downburst winds',
        'Driest month',
        'Drifting snow',
        'Drought',
        'Drought/Excessive heat',
        'Drowning',
        'Dry',
        'Dry conditions',
        'Dry hot weather',
        'Dry microburst',
        'Dry microburst 50',
        'Dry microburst 53',
        'Dry microburst 58',
        'Dry microburst 61',
        'Dry microburst 84',
        'Dry microburst winds',
        'Dry mircoburst winds',
        'Dryness',
        'Dry pattern',
        'Dry spell',
        'Dry weather',
        'Dust devil',
        'Dust devil',
        'Dust devil',
        'Dust devil/Waterspout',
        'Dust storm',
        'Dust storm',
        'Dust storm/High winds',
        'Early freeze',
        'Early frost',
        'Early frost',
        'Early rain',
        'Early snow',
        'Early snowfall',
        'Early snowfall',
        'Erosion/Coastal flood',
        'Excessive',
        'Excessive cold',
        'Excessive heat',
        'Excessive heat/Drought',
        'Excessively dry',
        'Excessive precipitation',
        'Excessive rain',
        'Excessive rainfall',
        'Excessive snow',
        'Excessive wetness',
        'Extended cold',
        'Extreme cold',
        'Extreme cold',
        'Extreme cold/Wind chill',
        'Extreme heat',
        'Extremely wet',
        'Extreme/Record cold',
        'Extreme wind chill',
        'Extreme wind chill',
        'Extreme wind chill/Blowing snow',
        'Extreme wind chill',
        'Extreme wind chill temperatures',
        'Falling snow/ice',
        'First frost',
        'First snow',
        'Flash flood',
        'Flash flood',
        'Flash flood/Flood',
        'Flash flood/Flood',
        'Flash flood from ice jams',
        'Flash flood/Heavy rain',
        'Flash flood/Heavy rain',
        'Flash flood',
        'Flash flood/Flood',
        'Flash flood/Thunderstorm wind',
        'Flash flood/Landslide',
        'Flash flood landslides',
        'Flash flood',
        'Flash flood/Street',
        'Flash flood winds',
        'Flash flood',
        'Flood',
        'Flood',
        'Flood flash',
        'Flood/Flash',
        'Flood/Flash flood',
        'Flood/Flash flood',
        'Flood/Flash flood',
        'Flood/Flash flood',
        'Flood/Flash flood',
        'Flood/Flash flood',
        'Flood/Heavy rain',
        'Flood',
        'Flood/Heavy rain',
        'Flood/Rain/Wind',
        'Flood/Rain/Wind',
        'Flood/River flood',
        'Flood',
        'Flood/Strong wind',
        'Flood watch',
        'Fog',
        'Fog/Cold temperatures',
        'Forest fires',
        'Freeze',
        'Freeze',
        'Freezing drizzle',
        'Freezing drizzle',
        'Freezing drizzle',
        'Freezing drizzle/Freezing',
        'Freezing fog',
        'Freezing fog',
        'Freezing rain',
        'Freezing rain',
        'Freezing rain',
        'Freezing rain/Sleet',
        'Freezing rain/Snow',
        'Freezing rain/Sleet',
        'Freezing rain/Sleet',
        'Freezing rain/Sleet/Light',
        'Freezing rain/Snow',
        'Freezing spray',
        'Frost',
        'Frost',
        'Frost/Freeze',
        'Frost/Freeze',
        'Frost/Freeze',
        'Funnel',
        'Funnel cloud',
        'Funnel cloud',
        'Funnel cloud',
        'Funnel cloud/Hail',
        'Funnel cloud',
        'Funnel',
        'Glaze',
        'Glaze',
        'Glaze ice',
        'Glaze/Ice storm',
        'Gradient wind',
        'Gradient wind',
        'Gradient wind',
        'Gradient wind',
        'Grass fires',
        'Ground blizzard',
        'Gustnado',
        'Gustnado',
        'Gusty lake wind',
        'Gusty thunderstorm wind',
        'Gusty thunderstorm wind',
        'Gusty wind',
        'Gusty wind',
        'Gusty wind/Hail',
        'Gusty wind/Heavy rain',
        'Gusty wind/Rain',
        'Gusty wind',
        'Gusty wind',
        'Gusty wind',
        'Hail',
        'Hail 0.75"',
        'Hail 0.75"',
        'Hail 0.75"',
        'Hail 0.88"',
        'Hail 0.88"',
        'Hail 1.00"',
        'Hail 1.00"',
        'Hail 1.25"',
        'Hail 1.50"',
        'Hail 1.75"',
        'Hail 1.75"',
        'Hail 1.75"',
        'Hail 2.00"',
        'Hail 2.25"',
        'Hail 2.75"',
        'Hail 4.50"',
        'Hail 0.75"',
        'Hail 0.80"',
        'Hail 0.88"',
        'Hail aloft',
        'Hail damage',
        'Hail flooding',
        'Hail/Icy roads',
        'Hailstorm',
        'Hailstorm',
        'Hailstorm',
        'Hail/Wind',
        'Hail/Wind',
        'Hard freeze',
        'Hazardous surf',
        'Heat',
        'Heatburst',
        'Heat/drought',
        'Heat/drought',
        'Heat wave',
        'Heat wave',
        'Heat wave/drought',
        'Heat wave',
        'Heavy lake snow',
        'Heavy mix',
        'Heavy precipatation',
        'Heavy precipitation',
        'Heavy precipitation',
        'Heavy rain',
        'Heavy rain',
        'Heavy rain',
        'Heavy rain/Flood',
        'Heavy rain/Wind',
        'Heavy rain effects',
        'Heavy rainfall',
        'Heavy rain/Flood',
        'Heavy rain/High surf',
        'Heavy rain/Lightning',
        'Heavy rain/Mudslides/Flood',
        'Heavy rain',
        'Heavy rain/Severe weather',
        'Heavy rain/Flood',
        'Heavy rain/Small stream urban',
        'Heavy rain/Snow',
        'Heavy rain/Urban flood',
        'Heavy rain/Urban flood/Winds',
        'Heavy rain/Wind',
        'Heavy seas',
        'Heavy shower',
        'Heavy shower',
        'Heavy snow',
        'Heavy snow',
        'Heavy snow/Blowing snow',
        'Heavy snow/High wind',
        'Heavy snow/Ice',
        'Heavy snow/Ice storm',
        'Heavy snow/Strong winds',
        'Heavy snow/Blizzard',
        'Heavy snow/Blizzard/Avalanche',
        'Heavy snow/Blowing snow',
        'Heavy snow/Freezing rain',
        'Heavy snow/Freezing rain',
        'Heavy snow/High wind',
        'Heavy snow/High wind',
        'Heavy snow/High wind',
        'Heavy snow/High winds/Flood',
        'Heavy snow/High winds/Freezing',
        'Heavy snow/Ice',
        'Heavy snow/Ice',
        'Heavy snow/Ice storm',
        'Heavy snowpack',
        'Heavy snow shower',
        'Heavy snow/Sleet',
        'Heavy snow/squalls',
        'Heavy snow/squalls',
        'Heavy snow/squalls',
        'Heavy snow/wind',
        'Heavy snow/Winter storm',
        'Heavy surf',
        'Heavy surf',
        'Heavy surf/Wind',
        'Heavy surf/Coastal flooding',
        'Heavy surf/High surf',
        'Heavy swell',
        'Heavy wet snow',
        'High',
        'High seas',
        'High surf',
        'High surf',
        'High surf advisory',
        'High surf advisory',
        'High swells',
        'High swells',
        'High temperature record',
        'High tide',
        'High water',
        'High waves',
        'Highway flooding',
        'High wind',
        'High wind',
        'High wind 48',
        'High wind 63',
        'High wind 70',
        'High wind/Heavy snow',
        'High wind/High tides',
        'High wind/Seas',
        'High wind/Blizzard',
        'High wind/Blizzard',
        'High wind/Blizzard/Freezing rain',
        'High wind damage',
        'High wind (g40)',
        'High wind/Heavy snow',
        'High wind/Low wind chill',
        'High wind',
        'High wind',
        'High wind',
        'High wind 55',
        'High wind 57',
        'High wind 58',
        'High wind 63',
        'High wind 66',
        'High wind 67',
        'High wind 73',
        'High wind 76',
        'High wind 80',
        'High wind 82',
        'High wind/Wind chill',
        'High wind/Coastal flood',
        'High wind/Cold',
        'High wind/Dust storm',
        'High wind/Seas',
        'High wind/Flood',
        'High wind/Heavy rain',
        'High wind/Heavy rain',
        'High wind/Snow',
        'High wind/Wind chill',
        'High wind/Wind chill/Blizzard',
        'Hot/dry',
        'Hot/dry pattern',
        'Hot pattern',
        'Hot spell',
        'Hot weather',
        'Hurricane',
        'Hurricane Edouard',
        'Hurricane Emily',
        'Hurricane Erin',
        'hurricane Felix',
        'Hurricane-generated swells',
        'Hurricane Gordon',
        'Hurricane Opal',
        'Hurricane Opal/High winds',
        'Hurricane/Typhoon',
        'Heavy rain',
        'Hyperthermia/Exposure',
        'Hypothermia',
        'Hypothermia/Exposure',
        'Hypothermia/Exposure',
        'Ice',
        'Ice/Snow',
        'Ice floes',
        'Ice fog',
        'Ice jam',
        'Ice jam flood',
        'Ice jam flood minor',
        'Icy road',
        'Ice pellets',
        'Icy road',
        'Ice/Snow',
        'Ice/Snow',
        'Ice storm',
        'Ice storm/Snow',
        'Ice storm/Blizzard',
        'Ice storm/Flash flood',
        'Ice/Strong winds',
        'Icy road',
        'Icy road',
        'Lack of snow',
        'Lake effect snow',
        'Lake effect snow',
        'Lake effect snow',
        'Lake flood',
        'Lakeshore flood',
        'Landslide',
        'Landslide',
        'Landslide/Urban flood',
        'Landslump',
        'Landslump',
        'Landspout',
        'Large wall cloud',
        'Late freeze',
        'Late season hail',
        'Late season snow',
        'Late season snow',
        'Late season snow',
        'Late season snow',
        'Light freezing rain',
        'Lightning',
        'Lightning',
        'Lightning.',
        'Lightning/Heavy rain',
        'Lightning/Thunderstorm wind',
        'Lightning/wind',
        'Lightning damage',
        'Lightning fire',
        'Lightning/Heavy rain',
        'Lightning injury',
        'Lightning/Thunderstorm wind',
        'Lightning/Thunderstorm wind',
        'Lightning wauseon',
        'Light snow',
        'Light snow',
        'Light snow',
        'Light snow/Sleet',
        'Light snow',
        'Light snow/Flurries',
        'Light snow/Freezing precip',
        'Lightning',
        'Local flash flood',
        'Local flood',
        'Local heavy rain',
        'Low temperature',
        'Low temperature record',
        'Low wind chill',
        'Major flood',
        'Marine accident',
        'Marine hail',
        'Marine high wind',
        'Marine mishap',
        'Marine strong wind',
        'Marine thunderstorm wind',
        'Marine thunderstorm wind',
        'Metro storm, may 26',
        'Microburst',
        'Microburst',
        'Microburst wind',
        'Mild/Dry pattern',
        'Mild/Dry pattern',
        'Mild pattern',
        'Minor flood',
        'Minor flood',
        'Minor flood',
        'Mixed precipitation',
        'Mixed precipitation',
        'Mixed precipitation',
        'Moderate snow',
        'Moderate snow',
        'Monthly precipitation',
        'Monthly rainfall',
        'Monthly rainfall',
        'Monthly snowfall',
        'Monthly snowfall',
        'Monthly temperature',
        'Mountain snows',
        'Mud/Rockslide',
        'Mudslide',
        'Mudslide',
        'Mudslide',
        'Mudslide/Landslide',
        'Mudslide',
        'Mudslide',
        'Mudslide',
        'Mudslide/Urban flood',
        'Near record snow',
        'None',
        'Non-severe hail',
        'Non-severe wind damage',
        'Non-thunderstorm wind',
        'Non-thunderstorm wind',
        'Normal precipitation',
        'Northern lights',
        'Non-severe weather',
        'Other',
        'Other',
        'Patchy dense fog',
        'Patchy ice',
        'Prolonged cold',
        'Prolonged cold',
        'Prolonged cold/Snow',
        'Prolonged rain',
        'Prolonged warmth',
        'Rain',
        'Rain/Wind',
        'Rain damage',
        'Heavy rain',
        'Rain/ssnow',
        'Rainstorm',
        'Rain/Wind',
        'Rapidly rising water',
        'Record cold',
        'Record cold',
        'Record cold',
        'Record cold/High wind',
        'Record cold/Frost',
        'Record cool',
        'Record dry month',
        'Record dryness',
        'Record/Excessive heat',
        'Record/Excessive rainfall',
        'Record heat',
        'Record heat',
        'Record heat wave',
        'Record high',
        'Record high',
        'Record high temperature',
        'Record high temperature',
        'Record low',
        'Record low rainfall',
        'Record may snow',
        'Record precipitation',
        'Record rainfall',
        'Record snow',
        'Record snow/Cold',
        'Record snow',
        'Record temperature',
        'Record temperature',
        'Record temperature',
        'Record temperature',
        'Record warmth',
        'Record warmth',
        'Record warmth',
        'Record warmth',
        'Record winter snow',
        'Red flag criteria',
        'Red flag fire wx',
        'Remnants of Floyd',
        'Rip current',
        'Rip current',
        'Rip current/Heavy surf',
        'Rip current/Heavy surf',
        'River flood/Stream flood',
        'River flood',
        'River flood',
        'River flood',
        'Rock slide',
        'Rogue wave',
        'Rotating wall cloud',
        'Rough seas',
        'Rough surf',
        'Rural flood',
        'Saharan dust',
        'Saharan dust',
        'Seasonal snowfall',
        'Seiche',
        'Severe cold',
        'Severe thunderstorm',
        'Severe thunderstorm',
        'Severe thunderstorm wind',
        'Severe turbulence',
        'Sleet',
        'Sleet/Freezing rain',
        'Sleet/Freezing rain',
        'Sleet/Ice storm',
        'Sleet/Rain/Snow',
        'Sleet/Snow',
        'Sleet storm',
        'Small hail',
        'Small hail',
        'Small hail',
        'Small stream',
        'Small stream',
        'Small stream/Urban flood',
        'Small stream/Urban flood',
        'Small stream flood',
        'Small stream flood',
        'Small stream/Urban flood',
        'Small stream/Urban flood',
        'Small stream flood',
        'Smoke',
        'Snow',
        'Snow',
        'Snow accumulation',
        'Snow accumulation',
        'Snow advisory',
        'Snow/Cold',
        'Snow/Heavy snow',
        'Snow/Ice',
        'Snow/Ice',
        'Snow/Ice storm',
        'Snow/Sleet',
        'Snow/Sleet',
        'Snow/Wind',
        'Snow/Bitter cold',
        'Snow/Blowing snow',
        'Snow/Cold',
        'Snow/Cold',
        'Snow drought',
        'Snowfall record',
        'Snow/Freezing rain',
        'Snow/Freezing rain',
        'Snow/Heavy snow',
        'Snow/High wind',
        'Snow/High wind/wind chill',
        'Snow/Ice',
        'Snow/Ice',
        'Snow/Ice storm',
        'Snowmelt flooding',
        'Snow/Rain',
        'Snow/Rain/Sleet',
        'Snow showers',
        'Snow/Sleet',
        'Snow/Sleet',
        'Snow/Sleet/Freezing rain',
        'Snow/Sleet/Rain',
        'Snow squall',
        'Snow squall',
        'Snow squall',
        'Snow squall',
        'Snowstorm',
        'Southeast',
        'Storm force winds',
        'Storm surge',
        'Storm surge/Tide',
        'Stream flood',
        'Street flood',
        'Street flood',
        'Strong wind',
        'Strong wind',
        'Strong wind gust',
        'Strong wind',
        'Strong wind',
        'Strong wind',
        'Summary august 10',
        'Summary august 11',
        'Summary august 17',
        'Summary august 21',
        'Summary august 2-3',
        'Summary august 28',
        'Summary august 4',
        'Summary august 7',
        'Summary august 9',
        'Summary jan 17',
        'Summary july 23-24',
        'Summary june 18-19',
        'Summary june 5-6',
        'Summary june 6',
        'Summary november 16',
        'Summary november 6-7',
        'Summary october 20-21',
        'Summary october 31',
        'Summary april 12',
        'Summary april 13',
        'Summary april 21',
        'Summary april 27',
        'Summary april 3',
        'Summary august 1',
        'Summary july 11',
        'Summary july 2',
        'Summary july 22',
        'Summary july 26',
        'Summary july 29',
        'Summary july 3',
        'Summary june 10',
        'Summary june 11',
        'Summary june 12',
        'Summary june 13',
        'Summary june 15',
        'Summary june 16',
        'Summary june 18',
        'Summary june 23',
        'Summary june 24',
        'Summary june 3',
        'Summary june 30',
        'Summary june 4',
        'Summary june 6',
        'Summary march 14',
        'Summary march 23',
        'Summary march 24',
        'Summary march 24-25',
        'Summary march 27',
        'Summary march 29',
        'Summary may 10',
        'Summary may 13',
        'Summary may 14',
        'Summary may 22',
        'Summary may 22 am',
        'Summary may 22 pm',
        'Summary may 26 am',
        'Summary may 26 pm',
        'Summary may 31 am',
        'Summary may 31 pm',
        'Summary may 9-10',
        'Summary september 18',
        'Summary september 25-26',
        'Summary september 20',
        'Summary september 23',
        'Summary september 3',
        'Summary september 4',
        'Temperature record',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thundersnow',
        'Thundersnow shower',
        'Thunderstorm',
        'Thunderstorm damage',
        'Thunderstorm damage',
        'Thunderstorm hail',
        'Thunderstorm',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind 50 mph',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind 50 mph',
        'Thunderstorm wind 52 mph',
        'Thunderstorm wind 56 mph',
        'Thunderstorm wind 59 mph',
        'Thunderstorm wind 59 mph',
        'Thunderstorm wind 59 mph.',
        'Thunderstorm wind 60 mph',
        'Thunderstorm wind 65 mph',
        'Thunderstorm wind 65 mph',
        'Thunderstorm wind 69 mph',
        'Thunderstorm wind 98 mph',
        'Thunderstorm wind/Awning',
        'Thunderstorm wind gusts 40 mph',
        'Thunderstorm wind gusts 50 mph',
        'Thunderstorm wind gusts 51 mph',
        'Thunderstorm wind gusts 52 mph',
        'Thunderstorm wind gusts 55 mph',
        'Thunderstorm wind gusts 60 mph',
        'Thunderstorm wind gusts 61 mph',
        'Thunderstorm wind/Hail',
        'Thunderstorm wind/Lightning',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind 13 mph',
        'Thunderstorm wind 2 mph',
        'Thunderstorm wind 50 mph',
        'Thunderstorm wind 52 mph',
        'Thunderstorm wind 53 mph',
        'Thunderstorm wind 53 mph',
        'Thunderstorm wind 60 mph',
        'Thunderstorm wind 61 mph',
        'Thunderstorm wind 62 mph',
        'Thunderstorm wind 63 mph',
        'Thunderstorm wind',
        'Thunderstorm wind/Flash flood',
        'Thunderstorm wind/Flood',
        'Thunderstorm wind/Flood',
        'Thunderstorm wind/Funnel cloud',
        'Thunderstorm wind/Funnel cloud',
        'Thunderstorm wind gusts',
        'Thunderstorm wind gusts 60 mph',
        'Thunderstorm wind/Hail',
        'Thunderstorm wind/Hail',
        'Thunderstorm wind/Hail',
        'Thunderstorm wind/Hail',
        'Thunderstorm wind/Heavy rain',
        'Thunderstorm wind/Heavy rain',
        'Thunderstorm wind/le cen',
        'Thunderstorm wind/Lightning',
        'Thunderstorm wind',
        'Thunderstorm wind/Small strea',
        'Thunderstorm wind/Urban flood',
        'Thunderstorm wind/Tree',
        'Thunderstorm wind/Tree',
        'Thunderstorm wind/Tree',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Tidal flood',
        'Tidal flood',
        'Tidal flood',
        'Tornado',
        'Tornado debris',
        'Tornado',
        'Tornado/Thunderstorm wind/Hail',
        'Tornado f0',
        'Tornado f1',
        'Tornado f2',
        'Tornado f3',
        'Tornado',
        'Tornado/Waterspout',
        'Tornado',
        'Torrential rain',
        'Torrential rain',
        'Tropical depression',
        'Tropical storm',
        'Tropical storm Alberto',
        'Tropical storm Dean',
        'Tropical storm Gordon',
        'Tropical storm Jerry',
        'Thunderstorm',
        'Thunderstorm/Heavy rain',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Thunderstorm wind 40 mph',
        'Thunderstorm wind 41 mph',
        'Thunderstorm wind 45 mph',
        'Thunderstorm wind 50 mph',
        'Thunderstorm wind 51 mph',
        'Thunderstorm wind 52 mph',
        'Thunderstorm wind 55 mph',
        'Thunderstorm wind 65 mph',
        'Thunderstorm wind/Lightning',
        'Thunderstorm wind damage',
        'Thunderstorm wind gusts 35 mph',
        'Thunderstorm wind gusts 40 mph',
        'Thunderstorm wind gusts 45 mph',
        'Thunderstorm wind gusts 45 mph',
        'Thunderstorm wind gusts 45 mph',
        'Thunderstorm wind gusts 58 mph',
        'Thunderstorm wind/Hail',
        'Thunderstorm wind',
        'Thunderstorm wind',
        'Tsunami',
        'Thunderstorm wind',
        'Typhoon',
        'Unseasonably cold',
        'Unseasonably cold',
        'Unseasonably cool',
        'Unseasonably cool/Wet',
        'Unseasonably dry',
        'Unseasonably hot',
        'Unseasonably warm',
        'Unseasonably warm/Dry',
        'Unseasonably warm/Wet',
        'Unseasonably warm/Wet',
        'Unseasonably warm year',
        'Unseasonably wet',
        'Unseasonal low temp',
        'Unseasonal rain',
        'Unusually cold',
        'Unusually late snow',
        'Unusually warm',
        'Unusually/Record warmth',
        'Unusually warm',
        'Urban stream flood/Small stream flood',
        'Urban stream flood/Small stream flood',
        'Urban stream flood/Small stream flood',
        'Urban stream flood/Small stream flood',
        'Urban flood',
        'Urban flood',
        'Urban flood',
        'Urban flood',
        'Urban flood',
        'Urban flood/Landslide',
        'Urban flood',
        'Urban stream flood/Small stream flood',
        'Urban stream flood/Small stream flood',
        'Urban stream flood/Small stream flood',
        'Urban stream flood/Small stream flood',
        'Urban stream flood/Small stream flood',
        'Urban stream flood/Small stream flood',
        'Urban stream flood/Small stream flood',
        'Urban stream flood/Small stream flood',
        'Urban stream flood/Small stream flood',
        'Urban stream flood/Small stream flood',
        'Urban stream flood/Small stream flood',
        'Urban stream flood/Small stream flood',
        'Very dry',
        'Very warm',
        'Fog',
        'Volcanic ash',
        'Volcanic ash',
        'Volcanic ash',
        'Volcanic ash',
        'Volcanic eruption',
        'Wake low wind',
        'Wall cloud',
        'Wall cloud/Funnel cloud',
        'Warm dry conditions',
        'Warm weather',
        'Waterspout',
        'Waterspout',
        'Waterspout',
        'Waterspout',
        'Waterspout/Funnel cloud',
        'Waterspout',
        'Waterspout/Tornado',
        'Waterspout/Tornado',
        'Waterspout/Tornado',
        'Waterspout/Tornado',
        'Waterspout',
        'Wet microburst',
        'Wet microburst',
        'Wet month',
        'Wet snow',
        'Wet weather',
        'Wet year',
        'Whirlwind',
        'Whirlwind',
        'Wildfire',
        'Wildfire',
        'Wildfire',
        'Wildfire/Forest fire',
        'Wildfire/Forest fire',
        'Wind',
        'Wind',
        'Wind advisory',
        'Wind/Wave',
        'Wind chill',
        'Wind chill/High wind',
        'Wind damage',
        'Wind damage',
        'Wind gusts',
        'Wind/Hail',
        'Wind',
        'Wind storm',
        'Winter mix',
        'Winter storm',
        'Winter storm/High wind',
        'Winter storm/High wind',
        'Winter storm/High wind',
        'Winter storm',
        'Winter weather',
        'Winter weather',
        'Winter weather mix',
        'Winter weather mix',
        'Winter mix',
        'Winter mix',
        'Winter mix',
        'Winter mix',
        'Wind'
    )
)
